### ISSUE TITLE
VoxelMap fails to load

### ISSUE THREAD

**Issue by securitypedant** [Parzivail-Modding-Team/ParziStarWarsMod#10]
VoxelMap is a very popular client mod that allows for the mapping of a Minecraft world. For some reason, when the Star Wars mod is added, VoxelMap stops working.

http://minecraft.curseforge.com/projects/voxelmap

I am more than happy to provide logs and feedback. I have a server with a lot of mods and my kids are so, so, so happy to have Star Wars, but we also need the map!

**Comment by parzivail** [comment]
This could be related to the LLibrary issue. I'll look into it. Thanks!

**Comment by parzivail** [comment]
Confirmed LLibrary issue, we'll look into a fix very soon.

**Comment by parzivail** [comment]
Whoops, forgot to close this. We fixed the LLibrary support in 1.2.5-beta.

**Comment by SecuritySimon** [comment]
I just got chance to test this, VoxelMap still doesn't load when the star wars mod is enabled. Does it work for you guys? Is there any log/diagnostics I can do on my end?

**Comment by parzivail** [comment]
That's peculiar! Are there log messages that show that VoxelMap *thinks*
it's loading? Do the keybinds work? If so, we may be cancelling an event
prematurely, and will look into it promptly

**Comment by SecuritySimon** [comment]
None of the Voxel key mappings work. I took a look at the liteloader.log, 

[12:05:26] [Client thread/INFO]: Successfully added "/Users/sthorpe/Library/Application Support/technic/modpacks/thorpe-city/mods/mod_wo$
[12:05:26] [Client thread/INFO]: Loading mod from com.thevoxelbox.voxelmap.litemod.LiteModVoxelMap
[12:05:26] [Client thread/INFO]: Successfully added mod VoxelMap version 1.5.18
[12:05:26] [Client thread/INFO]: Adding "/Users/sthorpe/Library/Application Support/technic/modpacks/thorpe-city/mods/mod_voxelMap_1.5.1$
[12:05:26] [Client thread/INFO]: Setting up "mod_voxelMap_1.5.18_for_1.7.10.litemod" as mod resource pack with identifier "VoxelMap"
[12:05:26] [Client thread/INFO]: Successfully added "/Users/sthorpe/Library/Application Support/technic/modpacks/thorpe-city/mods/mod_vo$
[12:05:26] [Client thread/INFO]: Initialising mod WorldEditCUI version 1.7.10_00
[12:05:26] [Client thread/INFO]: Initialising mod VoxelMap version 1.5.18

Looks like it thinks VoxelMap is loading. Yet no map displays onscreen nor any of the key mappings work.

**Comment by parzivail** [comment]
Hmm, that may be a universal LiteLoader problem. Have you tested any other
LiteLoader mods?

**Comment by parzivail** [comment]
I migrated this issue to the new issue tracker, so I'm closing this one. see the last remaining issue for more info.
